CREATE DATABASE IF NOT EXISTS epytodo;
USE epytodo;

DROP TABLE IF EXISTS user;
CREATE TABLE user
(
	user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) COLLATE utf8_bin NOT NULL,
	password VARCHAR(255) COLLATE utf8_bin NOT NULL,
	u_mail VARCHAR(255) COLLATE utf8_bin,
	u_tasks INT,
	u_tasks_completed INT
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS task;
CREATE TABLE task
(
	task_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) COLLATE utf8_bin NOT NULL,
	begin TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	end TIMESTAMP DEFAULT 0,
	t_description VARCHAR(2048) COLLATE utf8_bin,
	t_status INT DEFAULT 0
);

DROP TABLE IF EXISTS user_has_task;
CREATE TABLE user_has_task
(
	fk_user_id INT NOT NULL,
	fk_task_id INT NOT NULL
);
