CREATE DATABASE IF NOT EXISTS epytodo;
USE epytodo;

CREATE TABLE IF NOT EXISTS user
/* DROP TABLE IF EXISTS user;
   CREATE TABLE user */
(
	user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	u_mail VARCHAR(255),
	u_tasks INT,
	u_tasks_completed INT
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS task
/* DROP TABLE IF EXISTS task;
   CREATE TABLE task */
(
	task_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	begin TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	end TIMESTAMP DEFAULT 0,
	status INT DEFAULT 0,
	t_description VARCHAR(2048),

	user_own INT NOT NULL,
	CONSTRAINT `t_fk_user`
		FOREIGN KEY (`user_own`) REFERENCES `user` (`user_id`)
			ON DELETE CASCADE
			ON UPDATE RESTRICT
);
